name: CI

on:
  push:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            matrix:
                node-version:
                    - 10

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test
              env:
                  CI: true
                  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
                  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
                  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
